"""rtl-harness sync: generate the per-tool entry files of a consumer project (P3).

This pass ships the interface and the template layout only:

    scripts/sync/templates/common/    files every tool needs (.pre-commit-config.yaml, harness.yml)
    scripts/sync/templates/claude/    CLAUDE.md, .mcp.json
    scripts/sync/templates/copilot/   .github/copilot-instructions.md, .vscode/mcp.json
    (codex/, qwen/ are added later without touching anything else)

Generated files carry a "generated by rtl-harness sync" header; `sync --check` compares what
would be generated with what is on disk and exits 1 when they differ. Provisioning of the
ticketing scaffolding (rtl_harness.provision) runs first.
"""

from __future__ import annotations

import json

from . import __version__, paths
from .config import Config, load_config

TEMPLATES = paths.harness_root() / "scripts" / "sync" / "templates"
HEADER = f"generated by rtl-harness sync v{__version__} from harness.toml -- do not edit"


def available_tools() -> list[str]:
    return (
        sorted(p.name for p in TEMPLATES.iterdir() if p.is_dir() and p.name != "common")
        if TEMPLATES.is_dir()
        else []
    )


def planned_outputs(cfg: Config) -> list[dict]:
    """What sync will generate once implemented: (tool, template, destination)."""
    out = []
    for tool in ["common", *cfg.sync_tools]:
        d = TEMPLATES / tool
        if not d.is_dir():
            out.append({"tool": tool, "template": None, "dest": None, "note": "no templates yet"})
            continue
        for t in sorted(d.rglob("*.tmpl")):
            out.append(
                {
                    "tool": tool,
                    "template": t.relative_to(TEMPLATES).as_posix(),
                    "dest": t.relative_to(d).as_posix().removesuffix(".tmpl"),
                }
            )
    return out


def generate(cfg: Config) -> dict:
    return {
        "status": "unimplemented",
        "phase": "P3",
        "outputs": planned_outputs(cfg),
        "header": HEADER,
    }


def check(cfg: Config) -> dict:
    return {"status": "unimplemented", "phase": "P3", "outputs": planned_outputs(cfg)}


def cli(args) -> int:
    cfg = load_config()
    r = check(cfg) if args.check else generate(cfg)
    if args.json:
        print(json.dumps(r, indent=2, ensure_ascii=False))
    else:
        print("sync: not implemented in this pass (P3). Planned outputs:")
        for o in r["outputs"]:
            print(
                f"  [{o['tool']}] {o.get('template')} -> {o.get('dest')}"
                if o.get("template")
                else f"  [{o['tool']}] {o.get('note')}"
            )
    return 0 if not args.check else 0
